### ISSUE TITLE
Unencrypted data left behind after credentials are flushed

### ISSUE THREAD

**Issue by TheLocehiliosan** [elasticdog/transcrypt#74] opened 2020-02-21 23:13 UTC
Steps to reproduce:

1. Clone transcrypt-enabled repo
2. Run `transcrypt` with valid credentials
3. Run `git log -p` (displaying all change sets, included encrypted ones)
4. Run `transcrypt -f` (flushing the credentials)
5.
    A.  Run `for object in $(cat .git/refs/notes/textconv/crypt); do git show $object; done` (you'll see previously cached unencrypted data)

    or

    B.  Run `transcrypt` with **invalid credentials** (encrypted data should NOT be available at this time)
        Run `git log -p` (you'll see previously cached unencrypted data)

I looked into this, and the reason this data is left unencrypted is due to the setting `diff.crypt.cachetextconv=true`. I image this has been done for efficiency/speed, but the result is unencrypted data left behind. I can think of two ways to handle this problem.

1. Make `cachetextconv=true` optional, defaulting to `false`. This might be the simplest fix. Today this is hard-coded to `true`.
2. Upon `--flush`, hunt down any cached data. This data can be found by inspecting `<GIT_DIR>/refs/notes/textconv/crypt`. That will contain a list of git objects that need to be removed. This is probably more difficult, but might be best because then caching could be used.

**Comment by jmurty** [comment] 2020-05-30 14:24
Hi @TheLocehiliosan thanks for the report and reproduction steps. I confirmed the issue, and found that it also occurs when you uninstall transcrypt which also removes the creds and shouldn't leave behind (non-obvious) plaintext data.

I have applied a fix in the branch [74-clear-cached-plaintext-when-creds-flushed](https://github.com/elasticdog/transcrypt/tree/74-clear-cached-plaintext-when-creds-flushed), could you confirm that running `transcrypt -f` with the *transcrypt* script from that branch removes the unencrypted data?

The fix was relatively simple, though it does require a `git prune` to properly remove the plaintext objects which may not be safe to do without warning the user: 
https://github.com/elasticdog/transcrypt/pull/89/commits/80e9498f8cbc1e740a23847c915df7f7000eda3f#diff-2080fe2b0bfa1edd69c751a9d3978fb5R498-R501

**Comment by TheLocehiliosan** [comment] 2020-05-30 18:30
@jmurty - This is pretty close, but I think depending on how long the transcrypt credentials have been present, it is still possible for encrypted data to be present. `git prune` doesn't effect unreachable objects which have already been packed. I verified this by adjusting my reproduction steps like so:

1. Clone transcrypt-enabled repo

2. Run `transcrypt` with valid credentials

3. Run `git log -p` (displaying all change sets, included encrypted ones)

4. Run `git repack` (forcing all objects into packs)

5. Run `transcrypt -f` (flushing the credentials)

6. Run

```
for obj in \
  $(git rev-list --objects --no-walk \
  $(git fsck --unreachable | \
  grep '^unreachable commit' | \
  cut -d' ' -f3) | \
  cut -d' ' -f1); \
do git --no-pager show $obj; done
```

This shows the content of unreachable objects in the repo.

My guess is it might be necessary to repack after the pruning (I don't think repack will ever include unreachable objects when repacking).

**Comment by TheLocehiliosan** [comment] 2020-05-30 19:08
I did a few more tests myself. Seems like repacking might not be good enough. I was able to purge all the unreferenced objects via `git gc --prune=now`. But I'm not sure if there's a better way.

**Comment by jmurty** [comment] 2020-06-01 00:46
Thanks @TheLocehiliosan for the follow-up testing, and for catching my overlooking of packed objects.

I improved the tests to exercise the packed plaintext objects situation, and experimented with different ways to clear these out but the `git gc --prune=now --quiet` command seems like the best option.

The alternative is to run `git prune` then `git repack -ad` which doesn't seem like much less work, and might still leave objects hiding in current or future nooks and crannies of Git's objects DB. Since I don't understand the intricacies of Git's object storage well enough to be confident, it is safer to runt he cleanup command that is intended to be **the** cleanup command.

**Comment by TheLocehiliosan** [comment] 2020-06-01 04:28
@jmurty - I've tried this out, and it seems solid to me. 👍

I think the garbage collection **is** better than repack using `-a`. I think `-a` would result in a single pack, which isn't ideal for transferring data efficiently, so this seems to be the best way.

**Comment by elasticdog** [comment] 2020-06-01 20:42
Thank you @TheLocehiliosan for the report and ongoing testing...you're right that the caching was added to increase performance, especially when scrolling through history (via 5795360ff65221335cdd37f99c13ae2009a44ea0). One of the classic hard things in computer science :-)

**Comment by jmurty** [comment] 2020-06-02 13:22
The fix is now merged to the *master* branch, thanks very much for the report @TheLocehiliosan

**Closed by jmurty** 2020-06-02 13:22 UTC

**Comment by TheLocehiliosan** [comment] 2020-06-03 21:15
Thanks for the effort on this issue!
