### ISSUE TITLE
Diff problems when an empty file is marked for encryption

### ISSUE THREAD

**Issue by zeroem** [elasticdog/transcrypt#27] opened 2016-03-28 03:04 UTC
Steps to reproduce
  1. Create git repo
  1. Initialize Transcrypt
  1. Add Transcrypt rule to `.gitattributes`
    - `empty-file filter=crypt diff=crypt`
  1. Add/Commit the `.gitattributes` file
  1. Create the `empty-file`
    - `touch empty-file`
  1. Add the `empty-file`

At this point, if you run `git diff` there will be an empty diff, instead of no diff. If you run `git diff --exit-code` and then check the exit code `echo $?`, you'll see it exits with a `1` (indicating a difference), instead of a `0` (indicating no difference). If you reproduce these steps except for initializing transcrypt and configuring the rule for the empty file, `git diff --exit-code` will exit with a `0`.

From the user's perspective there's no indication what the problem is and it interferes with the ability to run any commands that depend on a clean working tree, eg `git rebase`.

**Comment by elasticdog** [comment] 2016-03-29 18:22
The behavior you're seeing is basically due the encryption metadata that is created by OpenSSL, where the first bytes of an encrypted file is always going to be "Salted__" followed by the salt for that particular file...this is true even for files with no content. If you look at the raw output of the empty file after it has been committed (or any encrypted file within the repo), you'll see that the beginning always looks the same due to this metadata (it's base64 encoded):

```
$ transcrypt --show-raw empty-file
==> empty-file <==
U2FsdGVkX1/0OoZQQeqeoCx58DHayX/lqCHgdKAGcGo=

$ echo "U2FsdGVkX1/0OoZQQeqeoCx58DHayX/lqCHgdKAGcGo=" | base64 --decode --input -
Salted__?PAꞠ,y?pj⏎
```

Off hand, I can't think of an easy way to fix the diff/exit code behavior via transcrypt, but will definitely give it some thought...

That said, I have a question and a suggested workaround. First, what is the use case for committing an empty encrypted file? Just preparation for when data is added into it later? The most simple workaround is to just add a single whitespace character into the file rather than making it empty. Or, perhaps a documentation comment on that file's purpose within your repo.

**Comment by zeroem** [comment] 2016-03-30 14:27
My situation was using a glob pattern to manage and entire directory structure. It happened to pick up a couple `.gitkeep` files as well. The workaround I used was what you suggested, adding some meaningless content to the files

**Comment by elasticdog** [comment] 2016-03-30 14:45
In that situation, you could also add a negative pattern to exclude the `.gitkeep` files explicitly (since you don't actually need those to be encrypted).

**Comment by elasticdog** [comment] 2016-03-30 14:46
Never mind, negative patterns don't work in `.gitattributes`.

**Comment by elasticdog** [comment] 2016-08-28 00:32
FYI, I've been toying with ideas on how to fix this, and you can use `[[ -s $filename ]]` in the clean filter to try and prevent encrypting empty files, but the problem is then with the smudge filter which processes via STDIN. I've tried a couple of methods to read data from STDIN to determine if it's empty or not, but I could not reliably handle empty files and the smudge filter still fails.

I'll keep thinking on this.

**Comment by elasticdog** [comment] 2016-08-28 04:38
I went barking up the wrong tree trying to follow this http://unix.stackexchange.com/a/33055, but I think actually adapting the code I had already written for #23 will work here. I'll see if I can't push something shortly.

**Comment by elasticdog** [comment] 2016-08-28 20:27
This should be fixed by the work done in #29 if you want to give that branch a shot. I'll be merging that into master and cutting a new release once I have a bit more time to kick the tires on those changes.

**Closed** 2016-08-29 22:29 UTC

**Comment by zeroem** [comment] 2016-09-06 16:39
Thanks, I'll give it a go and let you know how it works out.

**Comment by zeroem** [comment] 2016-09-06 16:43
This is working great, thank you!

**Comment by elasticdog** [comment] 2016-09-06 18:10
Glad to hear it! You're welcome, and sorry it took me so long to come up with a clean solution :-)
